"""
Orchestrator with:
- 21 agents (9 specialists + 12 regional Feds)
- 4 horizons per agent (6m, 12m, 3y, 10y)
- 2-round collaboration (outliers see consensus and may revise)
- Master derivation report generated by Chief
"""
import asyncio
import json
import random
import re
from datetime import datetime
import anthropic
from backend.data import activity_log as AL

from backend.agents.base_agent import (
    AgentContext, AgentResult, BaseAgent, HORIZONS, HorizonOutput,
)
from backend.agents.agent_01_behavioral import agent as a1
from backend.agents.agent_02_nlp import agent as a2
from backend.agents.agent_03_history import agent as a3
from backend.agents.agent_04_academic import agent as a4
from backend.agents.agent_05_projections import agent as a5
from backend.agents.agent_06_fomc_minutes import agent as a6
from backend.agents.agent_07_macro_data import agent as a7
from backend.agents.agent_08_political import agent as a8
from backend.agents.agent_10_consensus import agent as a10
from backend.agents.regional_agents import REGIONAL_AGENTS

from backend.config import settings

# All agents — 9 specialists + 12 regional
SPECIALIST_AGENTS: list[BaseAgent] = [a1, a2, a3, a4, a5, a6, a7, a8, a10]
ALL_AGENTS: list[BaseAgent] = SPECIALIST_AGENTS + REGIONAL_AGENTS
# Pre-built O(1) lookup (populated after _AGENT_BY_ID function definition below)
_AGENT_BY_ID: dict[int, BaseAgent] = {}

# Collaboration parameters
OUTLIER_BPS_THRESHOLD = 28.0   # |delta - mean| > 28 bps → trigger Round 2 (was 30)
MAX_OUTLIERS_REVIEWED = 5       # review more outliers (was 3) — better consensus formation

# Confidence-based filtering / weighting
MIN_CONFIDENCE_FOR_INCLUSION = 0.30   # raised from 0.25 — keep only meaningful signals
CONFIDENCE_EXPONENT = 2.5              # raised from 2.0 — reward high-conviction more aggressively

# Committee disagreement penalty (Bayesian posterior tightness)
TIGHT_CONSENSUS_STD   = 22.0   # bps stdev — below this, agents agree → confidence boost
WIDE_DISAGREEMENT_STD = 65.0   # bps stdev — above this, scattered → confidence penalty
CONSENSUS_BOOST       = 1.18   # tight consensus adds 18% to aggregate confidence
DISAGREEMENT_PENALTY  = 0.78   # wide spread cuts aggregate confidence by 22%
MAX_AGGREGATE_CONF    = 0.93   # cap aggregate confidence (never claim certainty)

_WEIGHT_OVERRIDES: dict[int, float] = {}
_ADAPTIVE_MULTIPLIERS: dict[int, float] = {}  # set by adaptive_weights()


def apply_weight_override(agent_id: int, weight: float):
    _WEIGHT_OVERRIDES[agent_id] = weight


async def compute_adaptive_weights(db, event: dict | None = None) -> dict[int, float]:
    """
    Auto-tune weights based on:
    1. Historical accuracy (from feedback_entry divergences)
    2. Current event type (FOMC/CPI/NFP boosts relevant agents)
    3. Capped at [0.5×, 2.0×] multiplier
    """
    from sqlalchemy import select, func
    from backend.database.models import FeedbackEntry
    multipliers: dict[int, float] = {}

    # ── Accuracy-based tuning ──────────────────────────────────────────────
    try:
        result = await db.execute(
            select(FeedbackEntry.agent_id,
                   func.avg(FeedbackEntry.divergence_bps).label("avg_div"),
                   func.count(FeedbackEntry.id).label("n"))
            .group_by(FeedbackEntry.agent_id)
            .having(func.count(FeedbackEntry.id) >= 3)   # min 3 samples
        )
        rows = result.all()
        if rows:
            divs = [row.avg_div for row in rows]
            median_div = sorted(divs)[len(divs) // 2]
            for row in rows:
                if row.avg_div < median_div * 0.6:
                    multipliers[row.agent_id] = 1.35   # accurate → boost
                elif row.avg_div > median_div * 1.6:
                    multipliers[row.agent_id] = 0.65   # inaccurate → penalise
            if multipliers:
                AL.system_event(f"Adaptive weights: {len(multipliers)} agents adjusted from accuracy history")
    except Exception:
        pass

    # Enforce [0.5×, 2.0×] cap on all multipliers
    multipliers = {k: max(0.5, min(2.0, v)) for k, v in multipliers.items()}

    # ── Event-based boosts ─────────────────────────────────────────────────
    if event:
        label = event.get("label", "")
        if "FOMC" in label:
            for aid in [1, 5, 6]:   # Behavioral, Projections, FOMC_Minutes
                multipliers[aid] = max(multipliers.get(aid, 1.0), 1.4)
            AL.system_event(f"FOMC event: Behavioral/Projections/Minutes weights boosted 1.4×")
        elif "CPI" in label:
            for aid in [4, 7]:      # Academic (Taylor), Macro_Data
                multipliers[aid] = max(multipliers.get(aid, 1.0), 1.4)
            AL.system_event(f"CPI event: Academic/MacroData weights boosted 1.4×")
        elif "NFP" in label:
            for aid in [7]:         # Macro_Data
                multipliers[aid] = max(multipliers.get(aid, 1.0), 1.4)
            for aid in range(101, 113):  # All regional Feds (labor market)
                multipliers[aid] = max(multipliers.get(aid, 1.0), 1.25)
            AL.system_event(f"NFP event: MacroData + Regional Feds weights boosted")

    global _ADAPTIVE_MULTIPLIERS
    _ADAPTIVE_MULTIPLIERS = multipliers
    return multipliers


def _effective_weight(result: AgentResult, base_weight: float) -> float:
    w = _WEIGHT_OVERRIDES.get(result.agent_id, base_weight)
    # Apply adaptive multiplier (accuracy + event-based)
    w *= _ADAPTIVE_MULTIPLIERS.get(result.agent_id, 1.0)
    if result.limited_mode:
        w *= 0.3
    if result.agent_id == 10:  # Consensus premium
        w *= 1.5
    return max(0.1, w)  # floor at 0.1 — never zero


# O(1) agent lookup — built once at module load
_AGENT_BY_ID: dict[int, BaseAgent] = {}


def _build_agent_index():
    global _AGENT_BY_ID
    _AGENT_BY_ID = {a.agent_id: a for a in ALL_AGENTS}


# Build index at module load
_build_agent_index()


def _aggregate_horizon(valid: list[AgentResult], horizon: str) -> tuple[float, float]:
    """
    Bayesian-style precision-weighted aggregation with committee dynamics.

    Pipeline:
    1. Prune agents below MIN_CONFIDENCE_FOR_INCLUSION
    2. Compute precision-weighted mean (weight ∝ effective_weight × confidence^EXPONENT)
    3. Apply committee-disagreement adjustment:
       - Tight consensus (std < TIGHT_CONSENSUS_STD): +18% confidence boost
       - Wide disagreement (std > WIDE_DISAGREEMENT_STD): -22% confidence penalty
    4. Cap at MAX_AGGREGATE_CONF (never report certainty)
    """
    import statistics
    total_weight = 0.0
    weighted_delta = 0.0
    weighted_confidence = 0.0
    included_deltas: list[float] = []
    included_weights: list[float] = []

    for r in valid:
        h_conf = r.horizon_confidence(horizon)
        if h_conf < MIN_CONFIDENCE_FOR_INCLUSION:
            continue
        agent_obj = _AGENT_BY_ID.get(r.agent_id)
        base_weight = agent_obj.weight if agent_obj else 1.0
        w = _effective_weight(r, base_weight) * (h_conf ** CONFIDENCE_EXPONENT)
        delta = r.horizon_delta(horizon)
        weighted_delta += delta * w
        weighted_confidence += h_conf * w
        total_weight += w
        included_deltas.append(delta)
        included_weights.append(w)

    if total_weight == 0:
        return 0.0, 0.0

    weighted_delta /= total_weight
    weighted_confidence /= total_weight

    # Committee disagreement adjustment — quantify posterior tightness
    if len(included_deltas) >= 4:
        # Weighted standard deviation around the consensus
        var = sum(
            wi * (di - weighted_delta) ** 2
            for di, wi in zip(included_deltas, included_weights)
        ) / total_weight
        std = var ** 0.5

        if std < TIGHT_CONSENSUS_STD:
            weighted_confidence *= CONSENSUS_BOOST
        elif std > WIDE_DISAGREEMENT_STD:
            weighted_confidence *= DISAGREEMENT_PENALTY
        # Else: middle band — no adjustment

    # Cap at max aggregate confidence
    weighted_confidence = min(MAX_AGGREGATE_CONF, weighted_confidence)
    return weighted_delta, weighted_confidence


def _identify_outliers(valid: list[AgentResult], consensus_12m: float) -> list[AgentResult]:
    """Find agents whose 12m signal diverges materially from consensus."""
    outliers = []
    for r in valid:
        divergence = abs(r.horizon_delta("12m") - consensus_12m)
        if divergence > OUTLIER_BPS_THRESHOLD:
            outliers.append((divergence, r))
    outliers.sort(key=lambda t: -t[0])
    return [r for _, r in outliers[:MAX_OUTLIERS_REVIEWED]]


async def run_full_cycle(ctx: AgentContext, cycle_type: str = "scheduled") -> dict:
    """
    Two-round orchestration:
      Round 1: All 21 agents analyze independently
      Round 2: Outliers see consensus & may revise (collaboration)
    Then aggregate all 4 horizons + generate derivation report.
    """
    # ── ROUND 1: Independent analysis ──────────────────────────────────────
    AL.orchestrator_event(f"Cycle start: {len(ALL_AGENTS)} agents dispatched in parallel (Round 1)")

    tasks = [agent.run(ctx) for agent in ALL_AGENTS]
    raw_results = await asyncio.gather(*tasks, return_exceptions=True)

    valid: list[AgentResult] = []
    errors: list[dict] = []
    for agent, r in zip(ALL_AGENTS, raw_results):
        if isinstance(r, Exception):
            errors.append({"agent": agent.agent_name, "error": str(r)[:200]})
            AL.collect_failed(agent.agent_name, str(r)[:60])
        else:
            valid.append(r)
            AL.agent_done(r.agent_name, r.signal, r.rate_path_delta_bps, r.confidence)

    # First-pass 12m consensus
    consensus_12m, _ = _aggregate_horizon(valid, "12m")

    # ── ROUND 2: Collaboration on outliers ─────────────────────────────────
    outliers = _identify_outliers(valid, consensus_12m)
    revisions: dict[int, AgentResult] = {}

    if outliers:
        import statistics as _stat
        AL.orchestrator_event(f"Round 2: {len(outliers)} outlier agents reviewing consensus — {', '.join(o.agent_name for o in outliers)}")

        # Signal distribution
        signal_dist = {"hawkish": 0, "neutral": 0, "dovish": 0}
        for r in valid:
            signal_dist[r.signal] = signal_dist.get(r.signal, 0) + 1

        # Find the 3 agents CLOSEST to consensus (best counter-evidence vs random sample)
        agents_by_distance = sorted(
            valid,
            key=lambda r: abs(r.horizon_delta("12m") - consensus_12m)
        )
        anchors = agents_by_distance[:3]

        # Median + range for context
        all_12m = [r.horizon_delta("12m") for r in valid]
        median_12m = _stat.median(all_12m)
        lo, hi = min(all_12m), max(all_12m)

        async def review_outlier(orig: AgentResult) -> AgentResult:
            agent_obj = _AGENT_BY_ID.get(orig.agent_id)
            if agent_obj is None:
                return orig

            # Quantify exactly how far this outlier sits from the committee
            outlier_error_bps = orig.horizon_delta("12m") - consensus_12m
            error_direction = "MORE HAWKISH" if outlier_error_bps > 0 else "MORE DOVISH"

            # Build targeted feedback (not generic)
            anchor_reasoning = " | ".join(
                f"[{a.agent_name} {a.horizon_delta('12m'):+.0f}bps]: {a.reasoning[:120]}"
                for a in anchors
            )
            consensus_summary = (
                f"COMMITTEE CONSENSUS (12m): {consensus_12m:+.1f} bps "
                f"[median {median_12m:+.0f}, range {lo:+.0f}..{hi:+.0f}]. "
                f"Distribution: hawkish={signal_dist['hawkish']}, "
                f"neutral={signal_dist['neutral']}, dovish={signal_dist['dovish']} "
                f"(of {len(valid)}).\n"
                f"YOUR R1 OUTPUT IS {abs(outlier_error_bps):.0f} bps {error_direction} "
                f"than consensus. Reconsider the following:\n"
                f"  1. Are you over-weighting one data source vs peers?\n"
                f"  2. Are you assuming a regime shift others don't see?\n"
                f"  3. Could you be anchoring on a recent event peers have already discounted?\n\n"
                f"3 AGENTS CLOSEST TO CONSENSUS: {anchor_reasoning}\n\n"
                f"Either (a) provide stronger evidence to defend your contrarian view, "
                f"or (b) revise toward consensus. Epistemic humility is rewarded — "
                f"updating in light of new information is NOT weakness."
            )

            review_ctx = AgentContext(
                macro_snapshot_text=ctx.macro_snapshot_text,
                speeches_text=ctx.speeches_text,
                fomc_minutes_texts=ctx.fomc_minutes_texts,
                beige_book_text=ctx.beige_book_text,
                regional_stances_text=ctx.regional_stances_text,
                cme_probabilities=ctx.cme_probabilities,
                negative_examples=ctx.negative_examples,
                material_event=ctx.material_event,
                consensus_summary=consensus_summary,
                own_round1_output=(
                    f"signal={orig.signal}, 12m_delta={orig.rate_path_delta_bps:+.0f} bps, "
                    f"confidence={orig.confidence:.2f}, reasoning={orig.reasoning[:200]}"
                ),
            )
            try:
                revised = await agent_obj.run(review_ctx)
                revised.round = 2
                revised.revised = abs(revised.rate_path_delta_bps - orig.rate_path_delta_bps) > 5
                return revised
            except Exception:
                return orig

        review_results = await asyncio.gather(*[review_outlier(o) for o in outliers])
        for rev in review_results:
            revisions[rev.agent_id] = rev
            AL.agent_done(rev.agent_name, rev.signal, rev.rate_path_delta_bps, rev.confidence, revised=rev.revised)

    # Replace round-1 outputs with round-2 revisions
    final_results = [revisions.get(r.agent_id, r) for r in valid]

    # ── Multi-horizon aggregation ─────────────────────────────────────────
    horizon_aggregates: dict[str, dict] = {}
    for h in HORIZONS:
        delta, conf = _aggregate_horizon(final_results, h)
        # Determine signal at this horizon
        if delta >= 25:
            signal = "hawkish"
        elif delta <= -25:
            signal = "dovish"
        else:
            signal = "neutral"
        horizon_aggregates[h] = {
            "weighted_delta_bps": round(delta, 2),
            "confidence": round(conf, 3),
            "signal": signal,
        }

    # ── Summary log ───────────────────────────────────────────────────────
    for h in HORIZONS:
        agg = horizon_aggregates[h]
        AL.orchestrator_event(
            f"{h.upper()} forecast → {agg['signal'].upper()} {agg['weighted_delta_bps']:+.0f} bps "
            f"(conf {agg['confidence']:.0%})"
        )

    # ── Chief synthesis + derivation report (EN + KO in parallel) ────────
    AL.orchestrator_event("Chief synthesizing derivation report (EN + KO)…")
    report_en, report_ko = await asyncio.gather(
        _generate_derivation_report(final_results, horizon_aggregates, outliers, revisions, errors, ctx, lang="en"),
        _generate_derivation_report(final_results, horizon_aggregates, outliers, revisions, errors, ctx, lang="ko"),
    )

    return {
        "cycle_type": cycle_type,
        "timestamp": datetime.utcnow().isoformat(),
        "horizons": horizon_aggregates,
        "report_en": report_en,
        "report_ko": report_ko,
        "agent_results": [
            {
                "agent_id": r.agent_id,
                "agent_name": r.agent_name,
                "signal": r.signal,
                "rate_path_delta_bps": r.rate_path_delta_bps,
                "confidence": r.confidence,
                "horizons": {
                    h: {
                        "delta_bps": r.horizon_delta(h),
                        "confidence": r.horizon_confidence(h),
                        "rationale": (r.horizons[h].rationale if h in r.horizons else ""),
                    }
                    for h in HORIZONS
                },
                "weight_applied": _effective_weight(
                    r, (_AGENT_BY_ID[r.agent_id].weight if r.agent_id in _AGENT_BY_ID else 1.0)
                ),
                "limited_mode": r.limited_mode,
                "duration_ms": r.duration_ms,
                "round": r.round,
                "revised": r.revised,
                "reasoning": r.reasoning,
            }
            for r in final_results
        ],
        "errors": errors,
        "collaboration": {
            "outliers_reviewed": [r.agent_name for r in outliers],
            "agents_revised": [r.agent_name for r in revisions.values() if r.revised],
        },
        "report_text": report_ko,   # backward compat field keeps Korean
    }


async def _generate_derivation_report(
    results: list[AgentResult],
    horizon_aggregates: dict[str, dict],
    outliers: list[AgentResult],
    revisions: dict[int, AgentResult],
    errors: list[dict],
    ctx: AgentContext,
    lang: str = "en",
) -> str:
    """Chief generates a markdown derivation report in the requested language."""
    agent_rows = []
    for r in sorted(results, key=lambda x: x.agent_id):
        row = (
            f"| {r.agent_name} | {r.signal.upper()} | "
            f"{r.horizon_delta('6m'):+.0f} | {r.horizon_delta('12m'):+.0f} | "
            f"{r.horizon_delta('3y'):+.0f} | {r.horizon_delta('10y'):+.0f} | "
            f"{r.confidence:.2f} |"
        )
        if r.revised:
            row += " *(revised)*"
        agent_rows.append(row)
    agent_table = "\n".join(agent_rows)

    horizon_rows = "\n".join(
        f"| {h.upper()} | {horizon_aggregates[h]['weighted_delta_bps']:+.1f} bps | "
        f"{horizon_aggregates[h]['signal'].upper()} | {horizon_aggregates[h]['confidence']:.2f} |"
        for h in HORIZONS
    )

    outlier_text = ", ".join(o.agent_name for o in outliers) if outliers else "None — broad consensus"
    revised_text = ", ".join(r.agent_name for r in revisions.values() if r.revised) or "None"

    if lang == "ko":
        report_instruction = (
            "Write a derivation report in KOREAN (한국어) — under 700 characters — covering:\n"
            "1. **요약**: 4개 horizon 한 줄씩 요약\n"
            "2. **주요 데이터 동인**: 어떤 macro/연설/이벤트가 신호를 이끌었는지 (2-3개)\n"
            "3. **주요 이견**: 어느 에이전트들이 다른 방향이었는지, 왜\n"
            "4. **핵심 리스크**: 이 예측을 무효화할 수 있는 1-2개 시나리오"
        )
    else:
        report_instruction = (
            "Write a derivation report in ENGLISH — under 700 characters — covering:\n"
            "1. **Summary**: One line per horizon\n"
            "2. **Key data drivers**: Which macro/speech/event led the signal (2-3 items)\n"
            "3. **Key divergences**: Which agents differed and why\n"
            "4. **Key risks**: 1-2 scenarios that would invalidate this forecast"
        )

    prompt = f"""You are the Chief Macroeconomic Orchestrator. Generate a concise markdown derivation report.

## Aggregated Horizon Outputs
| Horizon | Delta | Signal | Confidence |
|---------|-------|--------|-----------|
{horizon_rows}

## Agent Outputs (delta in bps)
| Agent | Signal | 6M | 12M | 3Y | 10Y | Conf |
|-------|--------|-----|-----|----|----|------|
{agent_table}

## Collaboration
- Outliers reviewed: {outlier_text}
- Agents that revised: {revised_text}
- Failed agents: {len(errors)}

## Macro Snapshot
{ctx.macro_snapshot_text[:1200]}

## Material Event
{ctx.material_event or "None"}

{report_instruction}

Output ONLY the markdown report, no preamble.
"""
    client = anthropic.AsyncAnthropic(api_key=settings.ANTHROPIC_API_KEY)
    try:
        resp = await client.messages.create(
            model=settings.MODEL_ID,
            max_tokens=1500,
            messages=[{"role": "user", "content": prompt}],
        )
        return resp.content[0].text
    except Exception as e:
        return f"Report generation failed: {e}"
